version: '3.6'

services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: web/Dockerfile-dev
    volumes:
      - './web:/usr/app/web'
    environment:
      - PORT=3000
      - NODE_ENV=development
    ports:
      - '3000:3000'
      - '3001:3001'

  graphql:
    container_name: graphql
    build:
      context: ./
      dockerfile: graphql/Dockerfile-dev
    volumes:
      - './graphql:/usr/app/graphql'
    environment:
      - PORT=3030
      - NODE_ENV=development
    ports:
      - '3030:3030'
