version: '3.6'

services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: web/Dockerfile-prod
    ports:
      - 80:80
    environment:
      - NODE_ENV=production

  graphql:
    container_name: graphql
    build:
      context: ./
      dockerfile: graphql/Dockerfile-prod
    expose:
      - '3030'
    environment:
      - PORT=3030
      - NODE_ENV=production
